sudo: required

services:
  - docker

before_install:
  - docker build -t wchamara/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  wchamara/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: ""
  secret_access_key:
    secure: ""
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-058573957490"

  on:
    repo: ccweerasinghe1994/Docker-react 
    branches:    
        - master
