version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - /app/node_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev

    tty: true
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]

